version: "2.1"

volumes:
  settings:

services:
 
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.template
      args:
        - VITE_KIOSK_EMAIL=${VITE_KIOSK_EMAIL}
        - VITE_KIOSK_PASSWORD=${VITE_KIOSK_PASSWORD}
    ports:
      - "5173:80"
    restart: always

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    restart: always

  kiosko:
    image: bh.cr/balenalabs/browser-aarch64
    privileged: true
    network_mode: host
    volumes:
      - "settings:/data"
    environment:
      - LAUNCH_URL=http://localhost:5173
      - kiosko=1
      - ENABLE_GPU=1
      - SHOW_CURSOR=1
    depends_on:
      - frontend
      - backend