version: "2.1"

volumes:
  settings:

services:
 
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    restart: always

  kiosk:
    image: bh.cr/balenalabs/browser-aarch64
    privileged: true
    network_mode: host
    volumes:
      - "settings:/data"
    environment:
      - LAUNCH_URL=http://localhost:80
      - kiosko=1
      - ENABLE_GPU=1
      - SHOW_CURSOR=1
    depends_on:
      - frontend